Merkle Stream Script
nodeset-org/constellation pull request #381
Opened 2024-10-01 18:57 UTC by huy-nodeset

2024-10-01 19:11 UTC, huy-nodeset commented on scripts/submitMerkleClaim_autoupdate.ts
> +        const response = await axios.get(GITHUB_REPO_API, { headers });
Update to use basic JS

2024-10-01 19:11 UTC, huy-nodeset commented on scripts/submitMerkleClaim_autoupdate.ts
> +        const response = await axios.get(GITHUB_REPO_API, { headers });
Dont use axios

2024-10-01 19:16 UTC, huy-nodeset commented on .env.example
> +ROCKET_STORAGE_ADDRESS="FILL_ME_IN"
use Directory to get these addresses

2024-10-02 00:06 UTC, VVander requested changes

2024-10-02 00:06 UTC, VVander commented on .env.example
> +NETWORK="FILL_ME_IN"
I'd rather not add a network key to the env because 1) it's just for running this specific script locally and 2) it's confusing to have this alongside the specific env files for deployments and other things that reference networks (.env.staging, .ev.prod, etc). Probably better to just have it hard coded into the script as `holesky` and then we can manually change it for the mainnet deployment.

2024-10-02 00:06 UTC, VVander commented on scripts/submitMerkleClaim_autoupdate.ts
> +const DIRECTORY_ADDRESS = process.env.DIRECTORY_ADDRESS;
remember to add commented instructions for deployment

2024-10-02 23:51 UTC, VVander commented on .env.example
> +SUPERNODE_ADDRESS="FILL_ME_IN"
```suggestion
```

2024-10-03 00:14 UTC, jclapis approved these changes
Blind

2024-10-03 01:53 UTC, VVander approved these changes

2024-10-03 01:53 UTC, merged