Add Task for Deploying Arbitrary Implementations
nodeset-org/constellation pull request #386
Opened 2024-10-03 20:47 UTC by teddy-nodeset

2024-10-07 18:56 UTC, VVander requested changes

2024-10-07 18:56 UTC, VVander commented on scripts/shell/test_release_against_current.sh
> +  ADDRESSES=$(grep -Eo '(whitelistProxy|vCWETHProxy|vCRPLProxy|operatorDistributorProxy|merkleClaimStreamerProxy|yieldDistributorProxy|priceFetcherProxy|snap)\.address\s0x[a-fA-F0-9]{40}|directory de
change this to a translation script that directly returns the address references via the individual deployment logic used for each tag

2024-10-08 18:34 UTC, VVander requested changes

2024-10-08 18:34 UTC, VVander commented on tasks/upgradeTasks.ts
>    .addParam('proxy', 'The address of the proxy contract', undefined, types.string)
This task is actually not used in my upgrade tasks -- it's only used in the tasks that you wrote. I just moved it over to another file in my PR. So in your PR, you can just delete this task instead of renaming. I'll also suggest that you move all of your tasks (except for the one for encoding upgradeTo) over to the new file (upgradeTasks.ts). That way we can keep only encoding-related tasks located in adminTasks.ts and timelockTasks.ts.

2024-10-08 18:41 UTC, teddy-nodeset commented on tasks/upgradeTasks.ts
>    .addParam('proxy', 'The address of the proxy contract', undefined, types.string)
good call, I like that organization better! Updated

2024-10-08 18:59 UTC, VVander commented on tasks/upgradeTasks.ts
> +task("upgradeProxy", "Upgrades a proxy contract to a new implementation using upgrades.upgradeProxy")
```suggestion
task("upgradeProxy", "Upgrades a proxy contract to a new implementation using upgrades.upgradeProxy"). WILL NOT WORK ON DEPLOYMENTS WITH A TIMELOCK.
```

2024-10-08 19:00 UTC, VVander approved these changes

2024-10-10 20:04 UTC, VVander approved these changes

2024-10-10 20:05 UTC, merged